package com.test.demo


//Just like java, in Groovy exception handling is done.


//i =1/0 // There is ArthmeticException when you run this code.To handle this type of Exceptions, you can add the some code to handle it
	// This is where try-catch in to picture 

//try-catch-finally
//try-finally


//try-catch
//Once there is a errors, it executes the exception block and prints the message
try {
int i =1/0
}catch(Exception exp) {
	println "I'm inside the exception block"
	println exp.getCause()
	println exp.getMessage()
	exp.printStackTrace()
}